# Simple configuration file for prometheus service
# This is used in the /docker-compose.yml file

global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'jasmin-api'
    static_configs:
      - targets: [ 'jasmin-api:8000' ]
  - job_name: jasmin
    static_configs:
      - targets: ['jasmin:1401']
  - job_name: 'rabbitmq'
    static_configs:
      - targets: [ 'rabbit-mq:15692' ]
  - job_name: 'redis'
    static_configs:
      - targets: [ 'redis:6379' ]
